version: '2'

services:    
    kafka1:
        build:
            dockerfile: Dockerfile.kafka
            context: .
            args:
                broker_id: 1
                zookeeper_hosts: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
        links:
            - zookeeper1
            - zookeeper2
            - zookeeper3
    kafka2:
        build:
            dockerfile: Dockerfile.kafka
            context: .
            args:
                broker_id: 2
                zookeeper_hosts: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
        links:
            - zookeeper1
            - zookeeper2
            - zookeeper3
    kafka3:
        build:
            dockerfile: Dockerfile.kafka
            context: .
            args:
                broker_id: 3
                zookeeper_hosts: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
        links:
            - zookeeper1
            - zookeeper2
            - zookeeper3
    zookeeper1:
        build:
            context: ../../zookeeper
            dockerfile: Dockerfile.zookeeper
            args:
                myid: 1
    zookeeper2:
        build:
            context: ../../zookeeper
            dockerfile: Dockerfile.zookeeper
            args:
                myid: 2
    zookeeper3:
        build:
            context: ../../zookeeper
            dockerfile: Dockerfile.zookeeper
            args:
                myid: 3
    kafka_cli:
        build:
            context: .
            dockerfile: Dockerfile.kafka_client
        stdin_open: true
        tty: true
        depends_on:
            - kafka1
            - kafka2
            - kafka3
