version: '2'

services:
    zookeeper1:
        build:
            dockerfile: Dockerfile.zookeeper
            context: .
            args:
                myid: 1
    zookeeper2:
        build:
            dockerfile: Dockerfile.zookeeper
            context: .
            args:
                myid: 2
    zookeeper3:
        build:
            dockerfile: Dockerfile.zookeeper
            context: .
            args:
                myid: 3
    zkcli:
        build:
            dockerfile: Dockerfile.zkcli
            context: .
        stdin_open: true
        tty: true
        links:
            - zookeeper1
            - zookeeper2
            - zookeeper3
